version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./vector-db/storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped

  embedding-service:
    build: ./embedding-service
    ports:
      - "8001:8000"
    environment:
      - MODEL_NAME=all-MiniLM-L6-v2
    restart: unless-stopped
    volumes:
      - ./embedding-service/models:/app/models

  rag-api:
    build: ./rag-api
    ports:
      - "8000:8000"
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - EMBEDDING_SERVICE_URL=http://embedding-service:8000
    depends_on:
      - qdrant
      - embedding-service
    restart: unless-stopped
    volumes:
      - ./data:/app/data

networks:
  default:
    name: rag-network